### ISSUE TITLE
Add Go 1.22 mirror img, fix STABLE/OLDSTABLE tags

### ISSUE THREAD

**Issue by atc0005** [atc0005/go-ci#1372]
## TODO

- [x] Add Go 1.22 series mirror image Dockerfile
- Update Makefile
  - [x] Move Go 1.20 mirror build image to legacy section
  - [x] Set Go 1.21 mirror build image as `oldstable` tag
  - [x] Add entry to build Go 1.22 series mirror image
  - [x] Set Go 1.22 mirror build image as `stable` tag

## References

- https://github.com/atc0005/go-ci/pull/1137
