### ISSUE TITLE
Go 1.18 released

### ISSUE THREAD

**Issue by atc0005** [atc0005/go-ci#557]
## Overview

Need to refresh `oldstable` to use Go `1.17` and `stable` to use the new Go `1.18` version.

References to Go `1.16` can be removed entirely.

The Go `1.18rc1`-based `unstable` container can be updated to `1.18` for the time being until the first 1.19-based pre-release becomes available.

NOTE: golangci-lint is still not 1.18 "certified", so will need to build from source for the time being. This requires updating the `stable` variants to match the current `unstable` container, while keeping the `oldstable` container logic (e.g., install via official installation script) intact.

## TODO

- [x] update `oldstable` image to use Go `1.17`
- [x]  update `stable` image to use Go `1.18`
  - [ ]  update `stable` image to use same steps as `unstable` image for building/installing current `golangci-lint`
    - building from source is needed until `golangci-lint` officially supports Go `1.18` (and running within a Go 1.18 container)
    - not needed for `oldstable` image (now based on Go `1.17`)
- [x]  update `unstable` image to use Go `1.18`
  - GH-556
- [x]  remove any references to Go `1.16`

## References

- https://golang.org/doc/go1.18
- https://groups.google.com/g/golang-announce/c/6gJm7mgF6rw/m/5w-bU37mAQAJ
- https://github.com/golangci/golangci-lint/issues/2649

**Comment by atc0005** [comment]
Note to self:

Probably worth making changes in small steps.

Update unstable image to official Go 1.18 release, but keep the stable image on 1.17 for the time being for best compatibility with golangci-lint.

Not sure yet about the oldstable image.

**Comment by atc0005** [comment]
> Update unstable image to official Go 1.18 release

Using golangci-lint with Go 1.18 requires a new setting. Some linters are disabled when enabling Go 1.18 support.

See:

- https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1070528726

Example (borrowed from https://github.com/goreleaser/goreleaser/pull/2989):

```diff
diff --git a/.golangci.yaml b/.golangci.yaml
index 126b222f13..a0731d5063 100644
--- a/.golangci.yaml
+++ b/.golangci.yaml
@@ -1,3 +1,5 @@
+run:
+  go: 1.18
 linters:
   enable:
     - thelper
```

**Comment by atc0005** [comment]
Note: The golangci-lint v1.45.0 Docker images were updated to use Go 1.18 as the base:

- GH-564
- GH-565

Since we're postponing upgrading "stable" images for this project to Go 1.18, I may need to update the `stable-lint-only` image to explicitly use Go 1.17 as the base.

**Comment by atc0005** [comment]
Go 1.19beta1 has been released. Cross-post from https://github.com/atc0005/go-ci/issues/656#issuecomment-1159692035:

> It's time to update the images accordingly:
> 
> - Go 1.16 dropped, 1.17 becomes the `oldstable` version
> - Go 1.18 is used for `stable` variants
> - Go 1.19 is used for `unstable`

We'll need to drop any hard-coded Go 1.17 specific settings in golangci-lint and allow auto-detection to take place.

**Comment by atc0005** [comment]
Considering the core work complete. The process of updating the `disable` linters list to drop linters which have gained Go 1.18 compatibility will be an ongoing process.
