### ISSUE TITLE
Refresh list of disabled linters (due to Go 1.18+ incompatibilities) for golangci-lint v1.47.1 release

### ISSUE THREAD

**Issue by atc0005** [atc0005/go-ci#681]
## Overview

The `golangci-lint` `v1.47.0` release was expected to resolve most Go 1.18+ incompatibilities (bundled linters), but an issue with the test suite incorrectly flagged problematic linters as compatible. The `v1.47.1` release disables known incompatible linters incorrectly flagged as compatible in the `v1.47.0` release.

## TODO

I should perform the following actions:

- [ ] review the compatibility table on https://github.com/golangci/golangci-lint/issues/2649
- [ ] restore the `disabled` list to the `stable` and `unstable` copies of the golangci-lint config files
- [ ] populate the `disabled` list with any linters confirmed to have issues with Go 1.18+

## References

- #557 
- #568
- #658
- #675
- #676
- #680
