### ISSUE TITLE
Update `oldstable` image to Go 1.18.x, `stable` image to Go 1.19.x

### ISSUE THREAD

**Issue by atc0005** [atc0005/go-ci#698]
## Overview

- Go 1.17 just received its last update (1.17.13, covered by `go-ci` `v0.6.21` release)
- Go 1.19 is now the stable release, 1.18 is the oldstable release
- golangci-lint v1.48.0 complains (fails?) when building for Go 1.17.13

## TODO

- [x] update `oldstable` image to Go 1.18
- [x] update `stable` image to Go 1.19
- [x] update golangci-lint config file for `oldstable` image to reflect Go 1.18
- [x] update golangci-lint config file for `stable` image to reflect Go 1.19
- [x] switch all image Dockerfiles from building golangci-lint back to installing using the official `install.sh` script

## References

- Go 1.18
  - https://golang.org/doc/go1.18
  - https://groups.google.com/g/golang-announce/c/6gJm7mgF6rw/m/5w-bU37mAQAJ
- Go 1.19
  - https://golang.org/doc/go1.19
  - https://groups.google.com/g/golang-announce/c/hwjGDuSVZJo
